# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - master

# pool:
#   vmImage: 'windows-latest'

variables:
 NUGET_PATH: ‘C:\Tools\Nuget\nuget.exe’
 MSBUILD_PATH: ‘C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\MSBuild.exe’
 XUNIT_PATH: packages\xunit.runner.console.2.3.1\tools\net452
 UNITTEST_FOLDER: ‘.\tests\CiCdExample.Tests\bin\Release\’

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


# stages:
#  – build
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      mkdir "$test"

# build_job:
# stage: build
# only:
# – branches
# script:
# – ‘& “$env:NUGET_PATH” restore’
# – ‘& “$env:MSBUILD_PATH” /p:Configuration=Release /clp:ErrorsOnly’
# – ‘& “$env:MSBUILD_PATH” src\CiCdExample\CiCdExample.csproj /p:DeployOnBuild=true /p:Configuration=Release /P:PublishProfile=FolderProfile.pubxml’
# artifacts:
# expire_in: 20 days
# paths:
# – ‘.\src\CiCdExample\bin\Release\Publish\’
# – ‘$env:UNITTEST_FOLDER’
# – ‘.\$env:XUNIT_PATH\*.*’

# test_job:
# stage: test
# only:
# – branches
# script:
# – ‘& “$env:XUNIT_PATH\xunit.console.exe” “$env:UNITTEST_FOLDER\CiCdExample.Tests.dll”‘
# dependencies:
# – build_job

# deploy_job:
# stage: deploy
# only:
# – branches
# script:
# – ‘xcopy /y /s “.\src\CiCdExample\bin\Release\Publish\*.*” “C:\Tools\inetpub\wwwroot\ci-cd-example”‘
# dependencies:
# – build_job
# – test_job
